# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  
  deploy:
    machine:
        enabled: true  
    steps:
       - checkout
       - run: 
          name: heroku container deploy
          command: |
            #  heroku plugins:install heroku-container-registry
            #  heroku container:login
            #  heroku container:push web --app $HEROKU_APP_NAME
            # #  heroku container:release web
             curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
             heroku container:login
             heroku container:push web --app $HEROKU_APP_NAME
             heroku container:release web --app $HEROKU_APP_NAME

